/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Database;

/**
 *
 * @author ionut
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

public class Customer extends javax.swing.JFrame {

    /**
     * Creates new form Customer
     */
    public Customer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CustomerIdText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        CustomerNameText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        CustomerAdressText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        CustomerNumberText = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        CustomerEmailText = new javax.swing.JTextField();
        InsertDataCustomerbtn = new javax.swing.JButton();
        clearCustomerbtn = new javax.swing.JButton();
        BackToMenuCustomerbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        jLabel1.setText("Customer Information");

        jLabel2.setText("Id");

        CustomerIdText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerIdTextActionPerformed(evt);
            }
        });

        jLabel3.setText("Name");

        CustomerNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerNameTextActionPerformed(evt);
            }
        });

        jLabel4.setText("Adress");

        jLabel5.setText("Number");

        jLabel6.setText("Email");

        CustomerEmailText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerEmailTextActionPerformed(evt);
            }
        });

        InsertDataCustomerbtn.setBackground(new java.awt.Color(102, 255, 102));
        InsertDataCustomerbtn.setText("Insert Data");
        InsertDataCustomerbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertDataCustomerbtnActionPerformed(evt);
            }
        });

        clearCustomerbtn.setForeground(new java.awt.Color(255, 0, 0));
        clearCustomerbtn.setText("Clear");
        clearCustomerbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearCustomerbtnActionPerformed(evt);
            }
        });

        BackToMenuCustomerbtn.setText("Back to menu");
        BackToMenuCustomerbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackToMenuCustomerbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(InsertDataCustomerbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                                .addComponent(clearCustomerbtn)
                                .addGap(91, 91, 91)
                                .addComponent(BackToMenuCustomerbtn))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel5)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(CustomerNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6)
                                .addComponent(CustomerEmailText, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                                .addComponent(CustomerAdressText)
                                .addComponent(CustomerNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(CustomerIdText, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CustomerIdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CustomerNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CustomerAdressText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CustomerNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CustomerEmailText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(InsertDataCustomerbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BackToMenuCustomerbtn)
                            .addComponent(clearCustomerbtn))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CustomerIdTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerIdTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CustomerIdTextActionPerformed

    private void CustomerNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CustomerNameTextActionPerformed

    private void InsertDataCustomerbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertDataCustomerbtnActionPerformed
       try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory_managemennt","root","ParolaCiobanu");
         
        // check if any of the text fields are empty
        if (CustomerIdText.getText().isEmpty() || CustomerNameText.getText().isEmpty() || CustomerAdressText.getText().isEmpty() || CustomerNumberText.getText().isEmpty() || CustomerEmailText.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "You cannot Insert Null data into the table");
        } else {
            String sql = "INSERT INTO Customer (Customer_Id, Customer_Name,Customer_Adress,Customer_Number,Customer_Email) VALUES (?, ?, ?, ?, ?)";
            PreparedStatement prepare = connection.prepareStatement(sql);
            
            prepare.setInt(1,Integer.parseInt(CustomerIdText.getText()));
            prepare.setString(2,CustomerNameText.getText());
            prepare.setString(3,CustomerAdressText.getText());
            prepare.setInt(4, Integer.parseInt(CustomerNumberText.getText()));
            prepare.setString(5,CustomerEmailText.getText());
            prepare.executeUpdate();
            JOptionPane.showMessageDialog(null,"Data successfully inserted");
        }
        connection.close();
        CustomerIdText.setText("");
        CustomerNameText.setText("");
        CustomerNumberText.setText("");
        CustomerAdressText.setText("");
        CustomerEmailText.setText("");
    } catch(SQLException e) {
        if (e.getErrorCode() == 1062) {
            JOptionPane.showMessageDialog(null,"Failed to insert data: Category ID already exists");
            CustomerIdText.setText("");
        } else {
            JOptionPane.showMessageDialog(null,e);
        }
    } catch(Exception e) {
        JOptionPane.showMessageDialog(null,e);
    }
    }//GEN-LAST:event_InsertDataCustomerbtnActionPerformed

    private void clearCustomerbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearCustomerbtnActionPerformed
        CustomerIdText.setText("");
        CustomerNameText.setText("");
        CustomerNumberText.setText("");
        CustomerAdressText.setText("");
        CustomerEmailText.setText("");
       
    }//GEN-LAST:event_clearCustomerbtnActionPerformed

    private void BackToMenuCustomerbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackToMenuCustomerbtnActionPerformed
        new Menu().setVisible(true);
        dispose();
    }//GEN-LAST:event_BackToMenuCustomerbtnActionPerformed

    private void CustomerEmailTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerEmailTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CustomerEmailTextActionPerformed

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackToMenuCustomerbtn;
    private javax.swing.JTextField CustomerAdressText;
    private javax.swing.JTextField CustomerEmailText;
    private javax.swing.JTextField CustomerIdText;
    private javax.swing.JTextField CustomerNameText;
    private javax.swing.JTextField CustomerNumberText;
    private javax.swing.JButton InsertDataCustomerbtn;
    private javax.swing.JButton clearCustomerbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
