/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Database;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author ionut
 */
public class Sales extends javax.swing.JFrame {

    /**
     * Creates new form Sales
     */
    public Sales() {
        initComponents();
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        SaleIdText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        SaleProductIdText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        SaleDateText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        InsertDataSalesbtn = new javax.swing.JButton();
        SaleCustomerIdText = new javax.swing.JTextField();
        clearSalesbtn = new javax.swing.JButton();
        BackToMenuSaleskbtn = new javax.swing.JButton();
        QuantitySaleText = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        jLabel1.setText("Sales Information");

        jLabel2.setText("Id");

        SaleIdText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaleIdTextActionPerformed(evt);
            }
        });

        jLabel3.setText("Product Id");

        SaleProductIdText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaleProductIdTextActionPerformed(evt);
            }
        });

        jLabel4.setText("Date");

        jLabel6.setText("Quantity sold");

        SaleDateText.setText("yyyy-mm-dd hh:mm:ss");
        SaleDateText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaleDateTextActionPerformed(evt);
            }
        });

        jLabel5.setText("Customer Id");

        InsertDataSalesbtn.setBackground(new java.awt.Color(102, 255, 102));
        InsertDataSalesbtn.setText("Insert Data");
        InsertDataSalesbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertDataSalesbtnActionPerformed(evt);
            }
        });

        clearSalesbtn.setForeground(new java.awt.Color(255, 0, 0));
        clearSalesbtn.setText("Clear");
        clearSalesbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearSalesbtnActionPerformed(evt);
            }
        });

        BackToMenuSaleskbtn.setText("Back to menu");
        BackToMenuSaleskbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackToMenuSaleskbtnActionPerformed(evt);
            }
        });

        QuantitySaleText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuantitySaleTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(InsertDataSalesbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                                .addComponent(clearSalesbtn)
                                .addGap(91, 91, 91)
                                .addComponent(BackToMenuSaleskbtn))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(SaleDateText, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(SaleProductIdText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                                .addComponent(SaleIdText, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(QuantitySaleText, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(SaleCustomerIdText, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SaleIdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SaleProductIdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SaleDateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SaleCustomerIdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(QuantitySaleText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                        .addComponent(InsertDataSalesbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BackToMenuSaleskbtn)
                            .addComponent(clearSalesbtn))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaleIdTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaleIdTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaleIdTextActionPerformed

    private void SaleProductIdTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaleProductIdTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaleProductIdTextActionPerformed

    private void SaleDateTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaleDateTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaleDateTextActionPerformed

    private void InsertDataSalesbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertDataSalesbtnActionPerformed
        try {
    Class.forName("com.mysql.cj.jdbc.Driver");
    Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory_managemennt","root","ParolaCiobanu");

    // check if any of the text fields are empty
    if (SaleIdText.getText().isEmpty() || SaleProductIdText.getText().isEmpty() || SaleDateText.getText().isEmpty() || SaleCustomerIdText.getText().isEmpty() || QuantitySaleText.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "You cannot Insert Null data into the table");
    } else {
        // Get product price from the Products table using the product ID
        String getProductPriceQuery = "SELECT Product_Price FROM Products WHERE Product_Id = ?";
        PreparedStatement getProductPriceStmt = connection.prepareStatement(getProductPriceQuery);
        getProductPriceStmt.setInt(1, Integer.parseInt(SaleProductIdText.getText()));
        ResultSet rs = getProductPriceStmt.executeQuery();
        double productPrice = 0.0;
        if (rs.next()) {
            productPrice = rs.getDouble("Product_Price");
        }

        // Calculate sales amount based on quantity sold and product price
        double salesAmount = Integer.parseInt(QuantitySaleText.getText()) * productPrice;

        // Insert data into the Sales table
        String insertSalesDataQuery = "INSERT INTO Sales (Sale_Id, Product_Id, Date_Sale, Quantity_Sold, Sales_Amount, Customer_Id) VALUES (?, ?, ?, ?, ?, ?)";
        PreparedStatement prepare = connection.prepareStatement(insertSalesDataQuery);
        int saleId = Integer.parseInt(SaleIdText.getText());
        prepare.setInt(1,saleId);
        prepare.setInt(2,Integer.parseInt(SaleProductIdText.getText()));
        Timestamp SaleDate = Timestamp.valueOf(SaleDateText.getText());
        prepare.setTimestamp(3, SaleDate);
        prepare.setInt(4,Integer.parseInt(QuantitySaleText.getText()));
        prepare.setDouble(5,salesAmount);
        prepare.setInt(6, Integer.parseInt(SaleCustomerIdText.getText()));
        prepare.executeUpdate();
        JOptionPane.showMessageDialog(null,"Data successfully inserted");
    }
    connection.close();
    SaleIdText.setText("");
    SaleProductIdText.setText("");
    SaleCustomerIdText.setText("");
    SaleDateText.setText("");
    QuantitySaleText.setText("");
} catch(SQLException e) {
    if (e.getErrorCode() == 1062) {
        JOptionPane.showMessageDialog(null,"Failed to insert data: Sale ID already exists");
        SaleIdText.setText("");
    } else {
        JOptionPane.showMessageDialog(null,e);
    }
} catch(Exception e) {
    JOptionPane.showMessageDialog(null,e);
}

    }//GEN-LAST:event_InsertDataSalesbtnActionPerformed

    private void clearSalesbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearSalesbtnActionPerformed
        SaleIdText.setText("");
        SaleProductIdText.setText("");
        SaleCustomerIdText.setText("");
        SaleDateText.setText("");
        QuantitySaleText.setText("");
    }//GEN-LAST:event_clearSalesbtnActionPerformed

    private void BackToMenuSaleskbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackToMenuSaleskbtnActionPerformed
        new Menu().setVisible(true);
        dispose();
    }//GEN-LAST:event_BackToMenuSaleskbtnActionPerformed

    private void QuantitySaleTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuantitySaleTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QuantitySaleTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Sales().setVisible(true);
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackToMenuSaleskbtn;
    private javax.swing.JButton InsertDataSalesbtn;
    private javax.swing.JTextField QuantitySaleText;
    private javax.swing.JTextField SaleCustomerIdText;
    private javax.swing.JTextField SaleDateText;
    private javax.swing.JTextField SaleIdText;
    private javax.swing.JTextField SaleProductIdText;
    private javax.swing.JButton clearSalesbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
